"""Provides various methods for the comparison of geometry of two (sets of)
polygonal meshes, which must have the same topology and.obj file format.

Copyright (C) 2025, Lenka Ptackova
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License 

This script is a part of implementation of methods supporting the paper
'Domain Decomposition for Mean Curvature Flow of Surface Polygonal Meshes'
"""

from read_write_mesh import vertex_position, read_mesh_obj
import matrices as mm

import math
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as clrs
import pandas as pd
import pymeshlab
ms = pymeshlab.MeshSet()
mesh_number = 0

def read_vertices(filename: str) -> np.ndarray:
    file = open(filename, 'r')
    V = []
    for line in file:
        if line.startswith('v '):
            V.append(vertex_position(line))
    return np.array(V, dtype = np.float32)


def compute_distances(mesh1_name: str, mesh2_name: str) -> np.ndarray:
    """Input: name of mesh file 1 (without .obj suffix), name of mesh file 2
    (without .obj suffix)

    The method expects the two meshes to be combinatorially equivalent.
    The method uses pymeshlab filter 'get_hausdorff_distance' to compute
    the minimal distance of each vertex of mesh1 from closest point
    over the mesh2.
    It further computes the distances between corresponding vertices, i.e.,
    the magnitude of absolute distances.

    It then divides the computed distances by the average edge length of
    mesh1 - makes the distances relative to the average edge lenght.
    It returns the relative RMS (root mean square), maximum, and mean
    of the computed distances - first for the pseudo Hausdorff distance (H_)
    and then for the vertex distances (V_).

    Returns: H_RMS H_max H_mean V_RMS V_max V_mean
    """
    global mesh_number
    ms.load_new_mesh(mesh1_name + ".obj")
    ms.load_new_mesh(mesh2_name + ".obj")
    data = ms.apply_filter('get_hausdorff_distance', targetmesh=mesh_number,\
                           sampledmesh=mesh_number + 1)
    mesh_number += 2

    V1, H1, F1 = read_mesh_obj(mesh1_name + ".obj")
    d0 = mm.create_d0(H1, V1)
    
    length = np.mean(np.linalg.norm(d0@V1, axis = 1)) # average edge length
    V2 = read_vertices(mesh2_name+ ".obj")

    vertex_distances = np.linalg.norm(V1 - V2, axis = 1)/length
    rms = np.sqrt(np.mean(vertex_distances**2))   
    return np.array([data['RMS']/length, data['max']/length,\
                     data['mean']/length, rms, max(vertex_distances),\
                     np.mean(vertex_distances)])


def store_distances(mesh1_name: str, mesh2_name: str, tick: str,\
                    outfile: str)-> None:
    """Input: name of mesh file 1 (without .obj suffix), name of mesh file 2
    (without .obj suffix), name of the file to print the
    computed distances into (without .txt suffix)

    The method prints first rms, max, mean of pseudo Hausdorff distances,
    then prints rms, max, mean of relative vertex distances, and then
    the log10 of all the distances (in the same order); all the values
    are printed in one line and are separated by space
    
    Output: None"""
    
    distances = compute_distances(mesh1_name, mesh2_name)
    f = open(outfile + ".txt", "a")
    it = mesh2_name.split("_")[-1]
    f.write(tick)
    for distance in distances:
        f.write(" {}".format(distance))
    for distance in distances:
        try:
            f.write(" {}".format(math.log10(distance)))
        except ValueError:
            f.write(" -7")        
    f.write("\n")
    f.close()
    return None


def compare_sets_of_meshes(mesh1_names: list, mesh2_names: list,\
                           ticks: list) -> str:
    """Input: list of reference meshes, list of candidate meshes

    The methods calls functions that caclulate the minimal distances of vertices
    of the reference meshes to the candidate meshes (pseudo Hausdorff distance)
    and relative distances of combinatorially corresponding vertices of the pairs
    of meshes. These distances are printed into a file output_file.

    Output: name of the output_file"""
    output_file = mesh1_names[-1]
    f = open(output_file + ".txt", "w")
    f.write('ticks H_RMS H_max H_mean V_RMS V_max V_mean')
    f.write(' H_logRMS H_logMax H_logMean V_logRMS V_logMax V_logMean\n')
    f.close()
    for i in range(len(mesh1_names)):
        store_distances(mesh1_names[i], mesh2_names[i], str(ticks[i]),\
                        output_file)
    return output_file + ".txt"


def plot_graphs(datafile_name: str) -> None:
    """Input: name of file where the datas to be read are stored

    The method expects the data structure as if generated by function
    compare_sets_of_meshes"""
    data = pd.read_csv(datafile_name, index_col = 0, delimiter=" ")
    df = pd.DataFrame(data)
    arithmetic = df[['H_RMS', 'H_max', 'H_mean','V_RMS', 'V_max', 'V_mean']]
    logarithmic = df[['H_logRMS', 'H_logMax', 'H_logMean',\
                      'V_logRMS', 'V_logMax', 'V_logMean']]

    fig, (ax1, ax2) = plt.subplots(1, 2,figsize=(15, 5))
    fig.suptitle('Hausdorff distance of ' + datafile_name)
    arithmetic.plot(ax = ax1, kind='line', style='.-')
    ax1.grid(axis='y')
    ax1.legend(loc='upper right', bbox_to_anchor=(1.1, 1))
    logarithmic.plot(ax = ax2, kind='line', style='.-')
    ax2.grid(axis='y')
    ax2.legend(loc='upper right', bbox_to_anchor=(1.1, 1))
##    plt.show()
    plt.savefig(datafile_name + ".png", dpi = 300)
    plt.close() 
    return None



#### =============================================================
#### THE BELLOW METHODS ARE FOR PLOTTING A MESH WITH VERTEX COLORS
#### REFLECTING THE RELATIVE DISTANCES OF CORRESPONDING VERTICES
#### =============================================================

def plot_distances_on_axis(fig, ax, mesh1_name: str, mesh2_name: str):
    """Computes the distances of corresponding vertices and divides
    them by the average edge lenght of mesh1. Each vertex of mesh1
    is then colored by the relative distance to the corresponding
    vertex of mesh2. The colored vertices of mesh1 are then plotted
    in axis ax of figure fig.
    """
    V1, H1, F1 = read_mesh_obj(mesh1_name + ".obj")
    d0 = mm.create_d0(H1, V1)
    averg_edge_length = np.mean(np.linalg.norm(d0@V1, axis = 1))
    V2 = read_vertices(mesh2_name + ".obj")

    vertex_distances = np.linalg.norm(V1-V2, axis=1) 

    colormap = plt.get_cmap("Spectral_r",12)
    coloring = vertex_distances/averg_edge_length
    p = ax.scatter(V1[:,0], V1[:,1], V1[:,2], vmin = 0, vmax = 1.5,\
                   c = coloring, cmap = colormap)
    ax.set_title((mesh2_name.split("/")[-1]).replace('.obj', ''))
    ax.grid(False)
    return p


def plot_3D_comparison(mesh1_names: list, mesh2_names: list) -> None:
    """The method takes in two lists containing filenames of meshes.
    For each pair (mesh1_names[i] and mesh2_names[i]) a subfigure
    of a 3D model will be ploted. Each subfigure is a scatter plot,
    where vertices of mesh1_names[i] are colored by their distances
    to the corresponding vertices of mesh2_names[i] divided by
    the average edge lenght of mesh1_names[i] mesh.
    """    
    if len(mesh1_names) != len(mesh2_names):
        print("Not the right number of meshes in lists")
        return None
    
    cols = math.ceil(math.sqrt(len(mesh1_names)))
    rows = math.ceil(len(mesh1_names)/cols)
    fig = plt.figure(figsize = (12,12))
    fig.suptitle("Relative distances of corresponding vertices")
    images = []
    for i in range(len(mesh1_names)):
        ax = fig.add_subplot(rows, cols, i+1, projection='3d')
        images.append(plot_distances_on_axis(fig, ax, mesh1_names[i],\
                                             mesh2_names[i]))
    fig.colorbar(images[-1],label = "Relative to the average length")
    plt.show()
    return None
