"""Mesh smoothing by implicit mean curvature flow with domain decomposition
and adapted Robin transmission conditions. This script serves for measuring
times.

Copyright (C) 2025, Lenka Ptackova
This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License 

This script is a part of implementation of
'Domain Decomposition for Mean Curvature Flow of Surface Polygonal Meshes'

The method uses backward Euler scheme and Laplacian on vector-valued 0-forms
that represent vertex position of the given mesh.
There are three Laplacians implemented:
1) "FU": scale–dependent umbrella operator of Fujiwara (1995)
    [doi:10.2307/2161293];
2) "AW": polygonal Laplacian of Alexa and Wardetzky (2011)
    [doi:10.1145/2010324.1964997],
3) "PV": polygonal Laplacian of Ptackova and Velho (2021)
    [doi:10.1016/j.cagd.2021.102002].

The method works with quadrilateral, triangle, and (prevalently) hexagonal meshes
generated by functions implemented in the script 'generate_meshes'. This restriction
is due to the fact, that the domain decomposition is adapted for the combinatorics
of these meshes.
"""

from read_write_mesh import read_mesh_obj
from decompose_mesh import decompose
import matrices as mm
import numpy as np
import math
from scipy.sparse import identity, diags, block_diag, csc_matrix
from scipy.sparse.linalg import spsolve
import time
import multiprocessing as mp

float_precis = np.float32
nVinRow = 0
param_p = 1


###---------------------------------------------------------

def normals_matrix(gamma, fv, V, prenormals_matrix, pre_projection_matrix):
    nGa = len(gamma)
    nV = len(V)
    iplus = gamma + 1
    iminus = gamma - 1
    
    ### Check if the gamma curve is closed:
    if iplus[-1] >= nV or iminus[0] < 0:
        iplus[-1] = gamma[0]
        iminus[0] = gamma[-1]
    
    prenormals = prenormals_matrix@V
    tangents = V[iplus,:] - V[iminus,:]
    tangent_norms = np.linalg.norm(tangents, axis = 1).reshape(nGa, 1)
    tangents = tangents/tangent_norms
    tang_comp_of_N = np.sum(np.multiply(prenormals,tangents),axis = 1).reshape(nGa,1)
    normal_norms = np.linalg.norm(prenormals-np.multiply(tang_comp_of_N,tangents),\
                                  axis = 1).reshape(nGa,1)
    projection_matrix = np.multiply(pre_projection_matrix.todense(),\
                                    tang_comp_of_N/tangent_norms)
    normals_matrix = (prenormals_matrix.todense() - projection_matrix)/normal_norms   
    return normals_matrix


def prenormals_matrix(gamma, fv, nV, nF):
    nGa = len(gamma)
    iplus = gamma + 1
    iminus = gamma - 1   
    ### Check if the gamma curve is closed:
    if iplus[-1] >= nV or iminus[0] < 0:
        iplus[-1] = gamma[0]
        iminus[0] = gamma[-1]
    prenormals_matrix = np.diag(np.ones(nF)@fv.sign()) -\
                        fv.sign().transpose()@fv
    pre_projection_matrix = np.zeros(nGa*nV, dtype = float_precis).\
                            reshape(nGa,nV)
    pre_projection_matrix[np.arange(nGa),iplus] = 1
    pre_projection_matrix[np.arange(nGa),iminus] = -1

    return csc_matrix(prenormals_matrix[gamma,:]), csc_matrix(pre_projection_matrix)

###---------------------------------------------------------

def Fujiwara(d0, V, fv, F, boundaryV, gammaV, part, prenormals_matrix = None,\
             pre_projection_matrix = None) -> np.ndarray:
    """Creates matrix representing Laplacian of Fujiwara (1995)"""
    vec_WE = np.linalg.norm(d0@V, axis=1)
    vec_WE = np.where(vec_WE < 10**(-8),1,vec_WE)
    vec_sum_WE = 0.5*np.abs(d0.transpose())@vec_WE
    sigma = 0.5*np.abs(d0.transpose())@np.ones(len(vec_WE))
    Lap = 0.5*diags(sigma/vec_sum_WE)@d0.transpose()@\
          diags(1/vec_WE)@d0
    Lap = Lap.todense()
    Lap[boundaryV,:] = np.zeros(len(V)*len(boundaryV)).\
                       reshape(len(boundaryV),len(V))
    if part == "lower":
        Lap[gammaV,:] = np.zeros(len(V)*len(gammaV)).\
                        reshape(len(gammaV),len(V))
    else:
        Lap[gammaV,:] = param_p*normals_matrix(gammaV, fv, V, prenormals_matrix,\
                                               pre_projection_matrix)     
    return csc_matrix(Lap, dtype = float_precis)


def AleWar(d0, R, F, H, V, fv, boundaryV, gammaV, part, prenormals_matrix = None,\
           pre_projection_matrix = None) -> np.ndarray:
    """Creates matrix representing Laplacian of Alexa & Wardetzky (2011)"""
    W1, WV = mm.W_matrices_AW(F, V)
    Lap = WV@d0.transpose()@R@W1@R.transpose()@d0
    Lap = Lap.todense()
    Lap[boundaryV,:] = np.zeros(len(V)*len(boundaryV)).\
                       reshape(len(boundaryV),len(V))
    if part == "lower":
        Lap[gammaV,:] = np.zeros(len(V)*len(gammaV)).\
                        reshape(len(gammaV),len(V))
    else:
        Lap[gammaV,:] = param_p*normals_matrix(gammaV, fv, V, prenormals_matrix,\
                                               pre_projection_matrix)   
    return csc_matrix(Lap, dtype = float_precis)


def PtaVel(fv, R, A, d0, d1, F, H, V, boundaryV, gammaV, part,\
           prenormals_matrix = None,\
           pre_projection_matrix = None) -> np.ndarray:
    """Creates matrix representing Laplacian of Ptackova & Velho (2021)"""
    WF, W1, WV = mm.W_matrices_PV(F, V)
    Lap = -WV@fv.transpose()@d1@A@W1@R.transpose()@d0
    Lap = Lap.todense()
    Lap[boundaryV,:] = np.zeros(len(V)*len(boundaryV)).\
                       reshape(len(boundaryV),len(V))
    if part == "lower":
        Lap[gammaV,:] = np.zeros(len(V)*len(gammaV)).\
                        reshape(len(gammaV),len(V))
    else:
        Lap[gammaV,:] = param_p*normals_matrix(gammaV, fv, V, prenormals_matrix,\
                                               pre_projection_matrix)   
    return csc_matrix(Lap, dtype = float_precis)


###---------------------------------------------------------

def MCF(Laplace, V, Vop, dt, boundaryV, interiorV, gammaV, part,\
        normalsThere):
    if part == "upper":
        V[gammaV,:] = Vop - dt*param_p*normalsThere
    else:
        V[gammaV,:] = Vop
            
    V[interiorV,:] += -dt*Laplace[interiorV,:][:,boundaryV]@V[boundaryV,:]
    Delta = csc_matrix(identity(len(interiorV)) +\
                       dt*Laplace[interiorV,:][:,interiorV])
    return spsolve(Delta, V[interiorV,:]) 


###---------------------------------------------------------
###---------------------------------------------------------

if __name__ == '__main__':
##    filename = "meshes/tri_anisotropic_cili_28000_200"
##    filename = "meshes/tri_anisotropic_cili_10080_120"
    filename = "meshes/quad_cilinder_wavy_10200_120"
##    filename = "meshes/quad_cilinder_wavy_28000_200"
    
    Laplacian = "AW"
    print(filename + " " + Laplacian + "\n topology, Laplacian, spsolve")
    maxIter, dt, typ, divRowV = 10, 0.05, 0, 0

    V, H, F = read_mesh_obj(filename + ".obj")

    if len(V) == int(filename.split("_")[-1]):
        nVinRow = int(math.sqrt(len(V)))
    else:
        nVinRow = int(filename.split("_")[-1])
        
    if typ == 0:                       
        typ = len(F[1])       

    if nVinRow*(divRowV + 1) >= len(V) or divRowV <= 1:
        divRowV = int(0.5*len(V)/nVinRow)

    
    ###-------------------------------------------------------
    ### Domain decomposition and topology matrices ###
    ###-------------------------------------------------------   
    submeshes = decompose(V, H, F, typ, divRowV, nVinRow)                 
    [V_A, H_A, F_A, boundary_A, gamma_A] = submeshes[0]
    [V_B, H_B, F_B, boundary_B, gamma_B] = submeshes[1]
    
    t0 = time.time()
    inputs = [(F_A, H_A, V_A), (F_B, H_B, V_B)]  
    with mp.Pool(2) as p:
        topology_A, topology_B = p.starmap(mm.create_incidence_matrices, inputs)
    fv_A, R_A, matrixA_A, d0_A, d1_A = topology_A
    fv_B, R_B, matrixA_B, d0_B, d1_B = topology_B

    prenormals_matrix_A, pre_projection_matrix_A =\
                         prenormals_matrix(gamma_A, fv_A, len(V_A), len(F_A))
    prenormals_matrix_B, pre_projection_matrix_B = \
                         prenormals_matrix(gamma_B, fv_B, len(V_B), len(F_B))
    print(time.time() - t0)
    
    int_A = np.array([x for x in range(len(V_A)) if x not in boundary_A])
    int_B = np.array([x for x in range(len(V_B)) if x not in boundary_B])

    inner_A = np.array([x for x in int_A if x not in gamma_A])
    inner_B = np.array([x for x in int_B if x not in gamma_B])


    
    ###-------------------------------------------------------
    
    if Laplacian == "FU":
        Lap_A = Fujiwara(d0_A, V_A, fv_A, F_A,\
                         boundary_A, gamma_A, "lower",)
        Lap_B = Fujiwara(d0_B, V_B, fv_B, F_B,\
                         boundary_B, gamma_B, "lower",)
    elif Laplacian == "AW":
        Lap_A = AleWar(d0_A, R_A, F_A, H_A, V_A, fv_A,\
                       boundary_A, gamma_A, "lower")
        Lap_B = AleWar(d0_B, R_B, F_B, H_B, V_B, fv_B,\
                       boundary_B, gamma_B, "lower")
    elif Laplacian == "PV":
        Lap_A = PtaVel(fv_A, R_A, matrixA_A, d0_A, d1_A, F_A, H_A, V_A,\
                       boundary_A, gamma_A, "lower")
        Lap_B = PtaVel(fv_B, R_B, matrixA_B, d0_B, d1_B, F_B, H_B, V_B,\
                       boundary_B, gamma_B, "lower")
    else:
        print("unknown Laplacian")

     
    curvatures_A = np.linalg.norm(Lap_A[inner_A,:]@V_A, axis = 1)
    curvatures_B = np.linalg.norm(Lap_B[inner_B,:]@V_B, axis = 1)

    
    ###-------------------------------------------------------
    ### The upper part is "forced" to align the normal direction on
    ### the interface to the normal direction of the lower part on 
    ### the interface; with weight given by the parameter p. The bigger 
    ### the parameter, the more aligned the normals are forced to be.
    ### Each iteration starts with the smoothing of the upper part.
    ### The lower part then takes the vertices on the interface of the
    ### upper part as its "future" fixed points, no directional
    ### derivative is involved.
    ### Ideally, the upper part should be the part which is overally
    ### further away from its corresponding minimal surface. 
    ### Thus it might be chosen by the user or estimated automatically
    ### by comparing the sum of mean curvatures of each part as bellow:


    if np.sum(curvatures_A) >= np.sum(curvatures_B) or typ == 5:
        part_A, part_B = "upper", "lower"
        
        E = np.min(np.linalg.norm(d0_A@V_A, axis=1))
        width = np.mean(np.linalg.norm(V_A[0:nVinRow,:] -\
                                       V_A[len(V_A)-nVinRow:len(V_A),:], axis=1))
        param_p = (((math.pi/width)**2 + 1)*((math.pi/E)**2 + 1))**(1/4)
        
        Lap_A = Lap_A.todense()
        Lap_A[gamma_A,:] += param_p*normals_matrix(gamma_A, fv_A, V_A,\
                                                   prenormals_matrix_A,\
                                                   pre_projection_matrix_A)
        Lap_A = csc_matrix(Lap_A, dtype = float_precis)
        
    else:
        part_A, part_B = "lower", "upper"
        
        E = np.min(np.linalg.norm(d0_B@V_B, axis=1))
        width = np.mean(np.linalg.norm(V_B[0:nVinRow,:] -\
                                       V_B[len(V_B)-nVinRow:len(V_B),:], axis=1))
        param_p = (((math.pi/width)**2 + 1)*((math.pi/E)**2 + 1))**(1/4)
        
        Lap_B = Lap_B.todense()
        Lap_B[gamma_B,:] += param_p*normals_matrix(gamma_B, fv_B, V_B,\
                                                   prenormals_matrix_B,\
                                                   pre_projection_matrix_B)
        Lap_B = csc_matrix(Lap_B, dtype = float_precis)

    ###-------------------------------------------------------
    ### The iteration process ###
    ###-------------------------------------------------------
        
    it = 0
    filenames = []
    t_linSys = 0
    t_Lap = 0
    while it< maxIter:
        it += 1
        t1 = time.time()  
        if part_A == "upper":
            normals_B = normals_matrix(gamma_B, fv_B, V_B, prenormals_matrix_B,\
                                       pre_projection_matrix_B)@V_B
            V_A[int_A,:] = MCF(Lap_A, V_A, V_B[gamma_B,:], dt, boundary_A,\
                               int_A, gamma_A, part_A, normals_B)
            V_B[int_B,:] = MCF(Lap_B, V_B, V_A[gamma_A,:], dt, boundary_B,\
                               int_B, gamma_B, part_B, None)
        else:
            normals_A = normals_matrix(gamma_A, fv_A, V_A, prenormals_matrix_A,\
                                       pre_projection_matrix_A)@V_A
            V_B[int_B,:] = MCF(Lap_B, V_B, V_A[gamma_A,:], dt, boundary_B,\
                               int_B, gamma_B, part_B, normals_A)
            V_A[int_A,:] = MCF(Lap_A, V_A, V_B[gamma_B,:], dt, boundary_A,\
                               int_A, gamma_A, part_A, None) 
        t_linSys += time.time()-t1

        
        ### CORRECTION  OF VERTICES ON THE INTERFACE (GAMMA):
        if typ == 3 or typ == 4:
            iplus = gamma_A + 1
            iminus = gamma_A - 1
            ### Check if the gamma curve is closed:
            if iplus[-1] >= len(V_A):
                iplus[-1] = gamma_A[0]
                iminus[0] = gamma_A[-1]
            V_A[gamma_A,:] = 0.25*(V_A[iminus,:] + V_A[iplus,:] +\
                                   V_A[gamma_A - nVinRow,:] +\
                                   V_B[gamma_B + nVinRow,:])
        elif typ == 6:
            if len(F_B[0]) == 6:
                for i in range(0,len(gamma_A),2):
                    V_A[gamma_A[i]]=1/3*(V_A[gamma_A[i]-1]+V_A[gamma_A[i]+1]+\
                                         V_A[gamma_A[i]-nVinRow])
                for i in range(1,len(gamma_A),2):
                    V_A[gamma_A[i]]=1/3*(V_A[gamma_A[i]-1]+V_A[gamma_A[i]+1]+\
                                         V_B[gamma_B[i]+nVinRow])                               
            elif len(F_B[0]) == 4:
                for i in range(0,len(gamma_A),2):
                    V_A[gamma_A[i]]=1/3*(V_A[gamma_A[i]-1]+V_A[gamma_A[i]+1]+\
                                         V_B[gamma_B[i]+nVinRow])
                for i in range(1,len(gamma_A),2): 
                    V_A[gamma_A[i]]=1/3*(V_A[gamma_A[i]-1]+V_A[gamma_A[i]+1]+\
                                         V_A[gamma_A[i]-nVinRow])                    
        V_B[gamma_B,:] = V_A[gamma_A,:]

        t2 = time.time()      
        if Laplacian == "FU":
            inputs = [(d0_A, V_A, fv_A, F_A, boundary_A, gamma_A, part_A,\
                       prenormals_matrix_A, pre_projection_matrix_A),\
                      (d0_B, V_B, fv_B, F_B, boundary_B, gamma_B, part_B,\
                       prenormals_matrix_B, pre_projection_matrix_B)]
            with mp.Pool(2) as p:
                Lap_A, Lap_B = p.starmap(Fujiwara, inputs)
        elif Laplacian == "AW":
            inputs = [(d0_A, R_A, F_A, H_A, V_A, fv_A, boundary_A,\
                       gamma_A, part_A, prenormals_matrix_A,\
                       pre_projection_matrix_A),\
                      (d0_B, R_B, F_B, H_B, V_B, fv_B, boundary_B,\
                       gamma_B, part_B, prenormals_matrix_B,\
                       pre_projection_matrix_B)]  
            with mp.Pool(2) as p:
                Lap_A, Lap_B = p.starmap(AleWar, inputs)
        elif Laplacian == "PV":
            inputs = [(fv_A, R_A, matrixA_A, d0_A, d1_A, F_A, H_A, V_A,\
                       boundary_A, gamma_A, part_A,\
                       prenormals_matrix_A, pre_projection_matrix_A),\
                      (fv_B, R_B, matrixA_B, d0_B, d1_B, F_B, H_B, V_B,\
                       boundary_B, gamma_B, part_B,\
                       prenormals_matrix_B, pre_projection_matrix_B)]
            with mp.Pool(2) as p:
                Lap_A, Lap_B = p.starmap(PtaVel, inputs)               
        t_Lap += time.time()-t2
    
    print("{:.6f}\n{:.6f}".\
          format(t_Lap/maxIter, t_linSys/maxIter))
    print("----------")
