"""Mesh smoothing by implicit mean curvature flow with domain decomposition
and alternating Schwarz method with overlap

Copyright (C) 2025, Lenka Ptackova
This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License 

This script is a part of implementation of methods supporting the paper
'Domain Decomposition for Mean Curvature Flow of Surface Polygonal Meshes'

The method uses backward Euler scheme and Laplacian on vector-valued 0-forms
that represent vertex position of the given mesh.
There are three Laplacians implemented:
1) "FU": scale–dependent umbrella operator of Fujiwara (1995)
    [doi:10.2307/2161293];
2) "AW": polygonal Laplacian of Alexa and Wardetzky (2011)
    [doi:10.1145/2010324.1964997],
3) "PV": polygonal Laplacian of Ptackova and Velho (2021)
    [doi:10.1016/j.cagd.2021.102002].

The method works with quadrilateral and triangle meshes generated by functions
implemented in the script 'generate_meshes'. This restriction is due to the fact,
that the domain decomposition is adapted for the combinatorics of these meshes.
"""

from read_write_mesh import read_mesh_obj, write_mesh_obj, rewrite_vertices
from decompose_mesh import decompose
import matrices as mm
import numpy as np
import math
from scipy.sparse import identity, diags, block_diag, csr_matrix
from scipy.sparse.linalg import spsolve

float_precis = np.float32
nVinRow = 0
overlap = 1


###---------------------------------------------------------

def Fujiwara(d0, V, fv, F, boundary)\
    -> np.ndarray:
    """Creates matrix representing Laplacian of Fujiwara (1995)"""
    vec_WE = np.linalg.norm(d0@V, axis=1)
    vec_WE = np.where(vec_WE < 10**(-8),1,vec_WE)
    vec_sum_WE = 0.5*np.abs(d0.transpose())@vec_WE
    sigma = 0.5*np.abs(d0.transpose())@np.ones(len(vec_WE))
    Lap = 0.5*diags(sigma/vec_sum_WE)@d0.transpose()@\
          diags(1/vec_WE)@d0
    Lap = Lap.todense()
    Lap[boundary,:] = np.zeros(len(V)*len(boundary)).\
                      reshape(len(boundary),len(V))     
    return csr_matrix(Lap, dtype = float_precis)


def AleWar(d0, R, F, H, V, fv, boundary)\
    -> np.ndarray:
    """Creates matrix representing Laplacian of Alexa & Wardetzky (2011)"""
    W1, WV = mm.W_matrices_AW(F, V)
    Lap = WV@d0.transpose()@R@W1@R.transpose()@d0
    Lap = Lap.todense()
    Lap[boundary,:] = np.zeros(len(V)*len(boundary)).\
                      reshape(len(boundary),len(V))
    return csr_matrix(Lap, dtype = float_precis)


def PtaVel(fv, R, A, d0, d1, F, H, V, boundary)\
    -> np.ndarray:
    """Creates matrix representing Laplacian of Ptackova & Velho (2021)"""
    WF, W1, WV = mm.W_matrices_PV(F, V)
    Lap = -WV@fv.transpose()@d1@A@W1@R.transpose()@d0
    Lap = Lap.todense()
    Lap[boundary,:] = np.zeros(len(V)*len(boundary)).\
                      reshape(len(boundary),len(V))
    return csr_matrix(Lap, dtype = float_precis)


###---------------------------------------------------------


def MCF(Laplace, V, dt, boundary, interior):
    V[interior,:] += -dt*Laplace[interior,:][:,boundary]@V[boundary,:]
    Delta = csr_matrix(identity(len(interior)) +\
                       dt*Laplace[interior,:][:,interior])
    return spsolve(Delta, V[interior,:])


###---------------------------------------------------------
###---------------------------------------------------------

def mcf_ddm_Schwarz(filename: str, Laplacian: str, maxIter: int, dt: float,\
                    divRowV: int = 0, overlapping: int = 1) -> None:
    """Mean curvature flow with aalternating Schwarz domain decomposition method.
    It works for quad and triangle meshes only.
    Arguments:
    filename - name of the .obj file, where the mesh is stored (without the suffix);
    Laplacian - "FU" for Fujiwara (1995), "AW" for Alexa & Wardetzky (2011),
                "PV" for Ptackova & Velho (2021);
    maxIter - number of iterations to be performed;
    dt - time step of each iteration;
    divRowV - the row, where decomposition should be done. Optional. By default,
    the input mesh is divided into two submeshes with approximately the same number
    of vertices;
    overlapping - the width (in the number of faces) of the overlap, by default is 1.

    Output: names of meshes, which has been stored in .obj files after each iteration"""
    
    V, H, F = read_mesh_obj(filename + ".obj")
    global nVinRow
    global overlap
    overlap = overlapping
                            
    typ = len(F[1])
    if typ == 3:
        nVinRow = int(math.sqrt(len(V)))
    elif typ == 4:
        if len(V) == int(filename.split("_")[-1]):
            nVinRow = int(math.sqrt(len(V)))
        else:
            nVinRow = int(filename.split("_")[-1])
    elif typ == 6:
        nVinRow = int(filename.split("_")[-1])

    if nVinRow*(divRowV + 1) >= len(V) or divRowV <= 1:
        divRowV = int(0.5*len(V)/nVinRow)
        print("Division row set to: {}".format(divRowV))
    
    
    ###-------------------------------------------------------
    ### Domain decomposition ###
    ###-------------------------------------------------------
    
    submeshes = decompose(V, H, F, typ, divRowV, nVinRow, overlap)                 
    [V_A, H_A, F_A, pre_boundary_A, gamma_A] = submeshes[0]
    [V_B, H_B, F_B, pre_boundary_B, gamma_B] = submeshes[1]
    fv_A, R_A, matrixA_A, d0_A, d1_A = mm.create_incidence_matrices(F_A, H_A, V_A)
    fv_B, R_B, matrixA_B, d0_B, d1_B = mm.create_incidence_matrices(F_B, H_B, V_B)

    boundary_A = np.array([x for x in range(len(V_A)) if x in pre_boundary_A or\
                           x in gamma_A])
    boundary_B = np.array([x for x in range(len(V_B)) if x in pre_boundary_B or\
                           x in gamma_B])
    
    inter_A = np.array([x for x in range(len(V_A)) if x not in boundary_A])
    inter_B = np.array([x for x in range(len(V_B)) if x not in boundary_B])
   
    ###-------------------------------------------------------
    
    if Laplacian == "FU":
        Lap_A = Fujiwara(d0_A, V_A, fv_A, F_A, boundary_A)
        Lap_B = Fujiwara(d0_B, V_B, fv_B, F_B, boundary_B)
    elif Laplacian == "AW":
        Lap_A = AleWar(d0_A, R_A, F_A, H_A, V_A, fv_A, boundary_A)
        Lap_B = AleWar(d0_B, R_B, F_B, H_B, V_B, fv_B, boundary_B)
    elif Laplacian == "PV":
        Lap_A = PtaVel(fv_A, R_A, matrixA_A, d0_A, d1_A, F_A, H_A, V_A,\
                       boundary_A)
        Lap_B = PtaVel(fv_B, R_B, matrixA_B, d0_B, d1_B, F_B, H_B, V_B,\
                       boundary_B)
    else:
        print("unknown Laplacian")

    curvatures_A = np.linalg.norm(Lap_A[inter_A,:]@V_A, axis = 1)
    curvatures_B = np.linalg.norm(Lap_B[inter_B,:]@V_B, axis = 1)
    print("Maximal mean curvatures:")
    print([max(curvatures_A), max(curvatures_B)])


    ###-------------------------------------------------------
    ### The iteration process ###
    ###-------------------------------------------------------
        
    it = 0
    filenames = []
    while it< maxIter:
        it += 1
        
        V_A[-nVinRow: ,:] = V_B[overlap*nVinRow:(overlap+1)*nVinRow,:]
        V_A[inter_A,:] = MCF(Lap_A, V_A, dt, boundary_A, inter_A)

        V_B[0:nVinRow,:] = V_A[len(V_A)-(1+overlap)*nVinRow:\
                               len(V_A)+(-overlap)*nVinRow,:]
        V_B[inter_B,:] = MCF(Lap_B, V_B, dt, boundary_B, inter_B)
            
        max_curv_A = max(np.linalg.norm(Lap_A[inter_A,:]@V_A, axis = 1))
        max_curv_B = max(np.linalg.norm(Lap_B[inter_B,:]@V_B, axis = 1))
        print([max_curv_A, max_curv_B])

        if it < maxIter:
            if Laplacian == "FU":
                Lap_A = Fujiwara(d0_A, V_A, fv_A, F_A, boundary_A)
                Lap_B = Fujiwara(d0_B, V_B, fv_B, F_B, boundary_B)
            elif Laplacian == "AW":
                Lap_A = AleWar(d0_A, R_A, F_A, H_A, V_A, fv_A, boundary_A)
                Lap_B = AleWar(d0_B, R_B, F_B, H_B, V_B, fv_B, boundary_B)
            elif Laplacian == "PV":
                Lap_A = PtaVel(fv_A, R_A, matrixA_A, d0_A, d1_A, F_A, H_A, V_A,\
                               boundary_A)
                Lap_B = PtaVel(fv_B, R_B, matrixA_B, d0_B, d1_B, F_B, H_B, V_B,\
                               boundary_B)

        V[0:len(V_A)-(1+overlap)*nVinRow,:] = V_A[:-(1+overlap)*nVinRow,:]   
        V[len(V_A)-(1+overlap)*nVinRow : ,:] = V_B
        rewrite_vertices(filename, V, "_{}_div{}_it{}_overlap{}_dt{}".\
                         format(Laplacian, divRowV, it, overlap, dt))
        nameParts = filename.split(sep="/")
        filenames.append(nameParts[0] + "/output/" + nameParts[1] +\
                         "_{}_div{}_it{}_overlap{}_dt{}".\
                         format(Laplacian, divRowV, it, overlap, dt))
        
       
    print("----------")
    return filenames

